<a href="https://colab.research.google.com/github/angadsidhu02/USAhousingData/blob/main/USAhousingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [69]:
data= pd.read_csv('/content/USA_Housing.csv')
df=pd.DataFrame(data)
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05

In [94]:
X=df.drop('Price', axis=1)
Y = df['Price']
X

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,79545.45857,5.682861,7.009188,4.09,23086.80050
1,79248.64245,6.002900,6.730821,3.09,40173.07217
2,61287.06718,5.865890,8.512727,5.13,36882.15940
3,63345.24005,7.188236,5.586729,3.26,34310.24283
4,59982.19723,5.040555,7.839388,4.23,26354.10947
...,...,...,...,...,...
4995,60567.94414,7.830362,6.137356,3.46,22837.36103
4996,78491.27543,6.999135,6.576763,4.02,25616.11549
4997,63390.68689,7.250591,4.805081,2.13,33266.14549
4998,68001.33124,5.534388,7.130144,5.44,42625.62016
4999,65510.58180,5.992305,6.792336,4.07,46501.28380

In [115]:
from sklearn.preprocessing import MinMaxScaler

selected_columns = ['Avg. Area Income', 'Avg. Area House Age'	, 'Avg. Area Number of Rooms'	, 'Avg. Area Number of Bedrooms'	, 'Area Population']

# Apply Min-Max Scaling
mx = MinMaxScaler()
X_scaled = mx.fit_transform(X)


# Create a new DataFrame with scaled values and original column names
X = pd.DataFrame(X_scaled, columns=selected_columns)
X

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,0.686822,0.441986,0.501502,0.464444,0.329942
1,0.683521,0.488538,0.464501,0.242222,0.575968
2,0.483737,0.468609,0.701350,0.695556,0.528582
3,0.506630,0.660956,0.312430,0.280000,0.491549
4,0.469223,0.348556,0.611851,0.495556,0.376988
...,...,...,...,...,...
4995,0.475738,0.754359,0.385619,0.324444,0.326351
4996,0.675097,0.633450,0.444024,0.448889,0.366362
4997,0.507135,0.670026,0.208534,0.028889,0.476515
4998,0.558419,0.420389,0.517579,0.764444,0.611282
4999,0.530715,0.486997,0.472678,0.460000,0.667088

In [116]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor


X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

reg = LinearRegression()
reg.fit(X_train, y_train)
reg.score(X_test, y_test)


#kf = KFold(n_splits = 5)

#for train_index, test_index in kf.split(X):
    #X_train, X_test = X[train_index], X[test_index]
    #y_train, y_test = Y[train_index], Y[test_index]

0.9146818498916266

In [117]:
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)
rfr.score(X_test, y_test)

0.8790203842829101